package espanolapp;



/**
 * this class is the frame for when the body part radio button is pressed in the
 * main frame, it stores the buttons and components of the frame
 *
 * @author Jazmin Vagha 16941106
 */
public class BodypartsButton extends javax.swing.JFrame {

    private SpanishDB db;

    /**
     * this method is the constructor for the class which calls the method to
     * initialize the components
     *
     * @param datab - an object of the main database, accesses the table in the
     * database
     */
    public BodypartsButton(SpanishDB datab) {
        db = datab;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eyesDialog = new javax.swing.JDialog();
        eyesPanel = new javax.swing.JPanel();
        ojos = new javax.swing.JLabel();
        okEyes = new javax.swing.JButton();
        mouthDialog = new javax.swing.JDialog();
        mouthPanel = new javax.swing.JPanel();
        boca = new javax.swing.JLabel();
        okMouth = new javax.swing.JButton();
        armsDialog = new javax.swing.JDialog();
        armsPanel = new javax.swing.JPanel();
        brazo = new javax.swing.JLabel();
        okArms = new javax.swing.JButton();
        handsDialog = new javax.swing.JDialog();
        handsPanel = new javax.swing.JPanel();
        manos = new javax.swing.JLabel();
        okHands = new javax.swing.JButton();
        feetDialog = new javax.swing.JDialog();
        feetPanel = new javax.swing.JPanel();
        pies = new javax.swing.JLabel();
        okFeet = new javax.swing.JButton();
        earsDialog = new javax.swing.JDialog();
        earsPanel = new javax.swing.JPanel();
        orejas = new javax.swing.JLabel();
        okEars = new javax.swing.JButton();
        noseDialog = new javax.swing.JDialog();
        nosePanel = new javax.swing.JPanel();
        nariz = new javax.swing.JLabel();
        okNose = new javax.swing.JButton();
        neckDialog = new javax.swing.JDialog();
        neckPanel = new javax.swing.JPanel();
        cuello = new javax.swing.JLabel();
        okNeck = new javax.swing.JButton();
        backDialog = new javax.swing.JDialog();
        backPanel = new javax.swing.JPanel();
        espalda = new javax.swing.JLabel();
        okBack = new javax.swing.JButton();
        legsDialog = new javax.swing.JDialog();
        legsPanel = new javax.swing.JPanel();
        piernas = new javax.swing.JLabel();
        okLegs = new javax.swing.JButton();
        helpDialog = new javax.swing.JDialog();
        helpPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        helpTitle = new javax.swing.JLabel();
        bodypartTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        bodypartsPanel = new javax.swing.JPanel();
        skeleton = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        ear = new javax.swing.JLabel();
        eyes = new javax.swing.JLabel();
        legs = new javax.swing.JLabel();
        nose = new javax.swing.JLabel();
        mouth = new javax.swing.JLabel();
        neck = new javax.swing.JLabel();
        arm = new javax.swing.JLabel();
        hand = new javax.swing.JLabel();
        feet = new javax.swing.JLabel();
        eyeButton = new javax.swing.JButton();
        mouthButton = new javax.swing.JButton();
        armsButton = new javax.swing.JButton();
        handButton = new javax.swing.JButton();
        feetButton = new javax.swing.JButton();
        earsButton = new javax.swing.JButton();
        noseButton = new javax.swing.JButton();
        neckButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        legButton = new javax.swing.JButton();
        rules = new javax.swing.JLabel();
        test = new javax.swing.JButton();

        eyesDialog.setTitle("                         EYES");
        eyesDialog.setMinimumSize(new java.awt.Dimension(315, 218));
        eyesDialog.setSize(new java.awt.Dimension(320, 220));
        eyesDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eyesPanel.setBackground(new java.awt.Color(255, 255, 255));
        eyesPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        eyesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ojos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        ojos.setText("ojos");
        eyesPanel.add(ojos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        okEyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okEyes.setText("OK");
        okEyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEyesActionPerformed(evt);
            }
        });
        eyesPanel.add(okEyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        eyesDialog.getContentPane().add(eyesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        mouthDialog.setTitle("                         MOUTH");
        mouthDialog.setSize(new java.awt.Dimension(320, 220));
        mouthDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mouthPanel.setBackground(new java.awt.Color(255, 255, 255));
        mouthPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        mouthPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boca.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        boca.setText("boca");
        mouthPanel.add(boca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        okMouth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okMouth.setText("OK");
        okMouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okMouthActionPerformed(evt);
            }
        });
        mouthPanel.add(okMouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        mouthDialog.getContentPane().add(mouthPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        armsDialog.setTitle("                         ARMS");
        armsDialog.setSize(new java.awt.Dimension(320, 220));
        armsDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        armsPanel.setBackground(new java.awt.Color(255, 255, 255));
        armsPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        armsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brazo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        brazo.setText("brazo");
        armsPanel.add(brazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        okArms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okArms.setText("OK");
        okArms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okArmsActionPerformed(evt);
            }
        });
        armsPanel.add(okArms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        armsDialog.getContentPane().add(armsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        handsDialog.setTitle("                         HANDS");
        handsDialog.setSize(new java.awt.Dimension(320, 220));
        handsDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        handsPanel.setBackground(new java.awt.Color(255, 255, 255));
        handsPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        handsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        manos.setText("manos");
        handsPanel.add(manos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        okHands.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okHands.setText("OK");
        okHands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okHandsActionPerformed(evt);
            }
        });
        handsPanel.add(okHands, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        handsDialog.getContentPane().add(handsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        feetDialog.setTitle("                         FEET");
        feetDialog.setSize(new java.awt.Dimension(320, 220));
        feetDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feetPanel.setBackground(new java.awt.Color(255, 255, 255));
        feetPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        feetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pies.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        pies.setText("PIES");
        feetPanel.add(pies, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        okFeet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okFeet.setText("OK");
        okFeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okFeetActionPerformed(evt);
            }
        });
        feetPanel.add(okFeet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        feetDialog.getContentPane().add(feetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        earsDialog.setTitle("                         EARS");
        earsDialog.setSize(new java.awt.Dimension(320, 220));
        earsDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        earsPanel.setBackground(new java.awt.Color(255, 255, 255));
        earsPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        earsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orejas.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        orejas.setText("OREJAS");
        earsPanel.add(orejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        okEars.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okEars.setText("OK");
        okEars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEarsActionPerformed(evt);
            }
        });
        earsPanel.add(okEars, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        earsDialog.getContentPane().add(earsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        noseDialog.setTitle("                         NOSE");
        noseDialog.setSize(new java.awt.Dimension(320, 220));
        noseDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nosePanel.setBackground(new java.awt.Color(255, 255, 255));
        nosePanel.setPreferredSize(new java.awt.Dimension(315, 218));
        nosePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nariz.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        nariz.setText("nariz");
        nosePanel.add(nariz, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        okNose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okNose.setText("OK");
        okNose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNoseActionPerformed(evt);
            }
        });
        nosePanel.add(okNose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        noseDialog.getContentPane().add(nosePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        neckDialog.setTitle("                         NECK");
        neckDialog.setSize(new java.awt.Dimension(320, 220));
        neckDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        neckPanel.setBackground(new java.awt.Color(255, 255, 255));
        neckPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        neckPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuello.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        cuello.setText("cuello");
        neckPanel.add(cuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        okNeck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okNeck.setText("OK");
        okNeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNeckActionPerformed(evt);
            }
        });
        neckPanel.add(okNeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        neckDialog.getContentPane().add(neckPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        backDialog.setTitle("                         BACK");
        backDialog.setSize(new java.awt.Dimension(320, 220));
        backDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        espalda.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        espalda.setText("espalda");
        backPanel.add(espalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        okBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okBack.setText("OK");
        okBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBackActionPerformed(evt);
            }
        });
        backPanel.add(okBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        backDialog.getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        legsDialog.setTitle("                         LEGS");
        legsDialog.setSize(new java.awt.Dimension(320, 220));
        legsDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        legsPanel.setBackground(new java.awt.Color(255, 255, 255));
        legsPanel.setPreferredSize(new java.awt.Dimension(315, 218));
        legsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piernas.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        piernas.setText("piernas");
        legsPanel.add(piernas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        okLegs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okLegs.setText("OK");
        okLegs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okLegsActionPerformed(evt);
            }
        });
        legsPanel.add(okLegs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 40));

        legsDialog.getContentPane().add(legsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        helpDialog.setTitle("                                                    HELP MENU");
        helpDialog.setBackground(new java.awt.Color(255, 255, 255));
        helpDialog.setFocusable(false);
        helpDialog.setResizable(false);
        helpDialog.setSize(new java.awt.Dimension(490, 310));
        helpDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                helpDialogWindowActivated(evt);
            }
        });
        helpDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpPanel.setBackground(new java.awt.Color(255, 196, 4));
        helpPanel.setFocusable(false);
        helpPanel.setPreferredSize(new java.awt.Dimension(490, 310));
        helpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        helpPanel.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 40));

        helpLabel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        helpLabel.setText("Use the home button to go back home");
        helpPanel.add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        helpTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        helpTitle.setText("HELP MENU");
        helpPanel.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        helpDialog.getContentPane().add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(656, 404));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodypartTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        bodypartTitle.setText("BODY PARTS");
        getContentPane().add(bodypartTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(250, 0, 0));
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 70, 34));

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 34));

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(0, 0, 222));
        helpButton.setText("HELP");
        helpButton.setBorder(null);
        helpButton.setBorderPainted(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 34));

        bodypartsPanel.setBackground(new java.awt.Color(255, 196, 4));
        bodypartsPanel.setPreferredSize(new java.awt.Dimension(656, 404));
        bodypartsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skeleton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espanolapp/Bart Simpson 02 - Skate - 256.png"))); // NOI18N
        bodypartsPanel.add(skeleton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 260));

        back.setPreferredSize(new java.awt.Dimension(110, 3));
        bodypartsPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 215, -1, -1));

        ear.setPreferredSize(new java.awt.Dimension(110, 3));
        bodypartsPanel.add(ear, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 110, -1, -1));

        eyes.setPreferredSize(new java.awt.Dimension(50, 3));
        bodypartsPanel.add(eyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        legs.setPreferredSize(new java.awt.Dimension(70, 3));
        bodypartsPanel.add(legs, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 270, -1, -1));

        nose.setPreferredSize(new java.awt.Dimension(40, 3));
        bodypartsPanel.add(nose, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 135, -1, -1));

        mouth.setPreferredSize(new java.awt.Dimension(70, 3));
        bodypartsPanel.add(mouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        neck.setPreferredSize(new java.awt.Dimension(85, 3));
        bodypartsPanel.add(neck, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 150, -1, -1));

        arm.setPreferredSize(new java.awt.Dimension(70, 3));
        bodypartsPanel.add(arm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        hand.setPreferredSize(new java.awt.Dimension(50, 3));
        bodypartsPanel.add(hand, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        feet.setPreferredSize(new java.awt.Dimension(70, 3));
        bodypartsPanel.add(feet, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 320, -1, -1));

        eyeButton.setBackground(new java.awt.Color(255, 255, 255));
        eyeButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        eyeButton.setText("EYES");
        eyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(eyeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        mouthButton.setBackground(new java.awt.Color(255, 255, 255));
        mouthButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mouthButton.setText("MOUTH");
        mouthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouthButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(mouthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        armsButton.setBackground(new java.awt.Color(255, 255, 255));
        armsButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        armsButton.setText("ARMS");
        armsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armsButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(armsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        handButton.setBackground(new java.awt.Color(255, 255, 255));
        handButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        handButton.setText("HANDS");
        handButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(handButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        feetButton.setBackground(new java.awt.Color(255, 255, 255));
        feetButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        feetButton.setText("FEET");
        feetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feetButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(feetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        earsButton.setBackground(new java.awt.Color(255, 255, 255));
        earsButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        earsButton.setText("EARS");
        earsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earsButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(earsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        noseButton.setBackground(new java.awt.Color(255, 255, 255));
        noseButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        noseButton.setText("NOSE");
        noseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noseButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(noseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        neckButton.setBackground(new java.awt.Color(255, 255, 255));
        neckButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        neckButton.setText("NECK");
        neckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neckButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(neckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        legButton.setBackground(new java.awt.Color(255, 255, 255));
        legButton.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        legButton.setText("LEGS");
        legButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legButtonActionPerformed(evt);
            }
        });
        bodypartsPanel.add(legButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        rules.setBackground(new java.awt.Color(255, 255, 255));
        rules.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        rules.setText("Press the names to see their translation");
        bodypartsPanel.add(rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        test.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        test.setText("TAKE THE TEST");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        bodypartsPanel.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        getContentPane().add(bodypartsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this method exits the program when the exit button is pressed
     *
     * @param evt - has the action event as a parameter for when the exit button
     * pressed
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    /**
     * this method takes you to the back to the start frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the home button
     * pressed
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new EspanolApp(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed
    /**
     * this method is the action for when the arms button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the arms button
     * pressed
     */
    private void armsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armsButtonActionPerformed
        armsDialog.setVisible(true);
    }//GEN-LAST:event_armsButtonActionPerformed
    /**
     * this method is the action for when the hands button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the hands
     * button pressed
     */
    private void handButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handButtonActionPerformed
        handsDialog.setVisible(true);
    }//GEN-LAST:event_handButtonActionPerformed
    /**
     * this method is the action for when the back button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the back button
     * pressed
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backDialog.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the eyes
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okEyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEyesActionPerformed
        eyesDialog.dispose();
    }//GEN-LAST:event_okEyesActionPerformed
    /**
     * this method is the action for when the eyes button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the eyes button
     * pressed
     */
    private void eyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeButtonActionPerformed
        eyesDialog.setVisible(true);
    }//GEN-LAST:event_eyeButtonActionPerformed
    /**
     * this method is the action for when the mouth button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the mouth
     * button pressed
     */
    private void mouthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouthButtonActionPerformed
        mouthDialog.setVisible(true);
    }//GEN-LAST:event_mouthButtonActionPerformed
    /**
     * this method is the action for when the feet button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the feet button
     * pressed
     */
    private void feetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feetButtonActionPerformed
        feetDialog.setVisible(true);
    }//GEN-LAST:event_feetButtonActionPerformed
    /**
     * this method is the action for when the ears button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the ears button
     * pressed
     */
    private void earsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earsButtonActionPerformed
        earsDialog.setVisible(true);
    }//GEN-LAST:event_earsButtonActionPerformed
    /**
     * this method is the action for when the nose button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the nose button
     * pressed
     */
    private void noseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noseButtonActionPerformed
        noseDialog.setVisible(true);
    }//GEN-LAST:event_noseButtonActionPerformed
    /**
     * this method is the action for when the neck button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the neck button
     * pressed
     */
    private void neckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neckButtonActionPerformed
        neckDialog.setVisible(true);
    }//GEN-LAST:event_neckButtonActionPerformed
    /**
     * this method is the action for when the leg button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the leg button
     * pressed
     */
    private void legButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legButtonActionPerformed
        legsDialog.setVisible(true);
    }//GEN-LAST:event_legButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the mouth
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okMouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okMouthActionPerformed
        mouthDialog.dispose();
    }//GEN-LAST:event_okMouthActionPerformed
    /**
     * this method is the actions that occur when the ok button in the arms
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okArmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okArmsActionPerformed
        armsDialog.dispose();
    }//GEN-LAST:event_okArmsActionPerformed
    /**
     * this method is the actions that occur when the ok button in the hands
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okHandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okHandsActionPerformed
        handsDialog.dispose();
    }//GEN-LAST:event_okHandsActionPerformed
    /**
     * this method is the actions that occur when the ok button in the feet
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okFeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okFeetActionPerformed
        feetDialog.dispose();
    }//GEN-LAST:event_okFeetActionPerformed
    /**
     * this method is the actions that occur when the ok button in the ears
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okEarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEarsActionPerformed
        earsDialog.dispose();
    }//GEN-LAST:event_okEarsActionPerformed
    /**
     * this method is the actions that occur when the ok button in the nose
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okNoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNoseActionPerformed
        noseDialog.dispose();
    }//GEN-LAST:event_okNoseActionPerformed
    /**
     * this method is the actions that occur when the ok button in the neck
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okNeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNeckActionPerformed
        neckDialog.dispose();
    }//GEN-LAST:event_okNeckActionPerformed
    /**
     * this method is the actions that occur when the ok button in the back
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBackActionPerformed
        backDialog.dispose();
    }//GEN-LAST:event_okBackActionPerformed
    /**
     * this method is the actions that occur when the ok button in the legs
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okLegsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okLegsActionPerformed
        legsDialog.dispose();
    }//GEN-LAST:event_okLegsActionPerformed

    /**
     * this method opens the test frame of the body parts when the take the test
     * button is pressed on the body part frame
     *
     * @param evt - has the action event as a parameter for when the take the
     * test button pressed
     */
    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        new BodypartTest(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testActionPerformed

    /**
     * this method is the actions that occur when the help button is pressed, a
     * dialog pops up with general help on the program
     *
     * @param evt - has the action event as a parameter for when help button
     * pressed
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpDialog.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the help
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        helpDialog.dispose();
    }//GEN-LAST:event_okActionPerformed
    /**
     * this method activates the help dialog when the program when the help
     * button is pressed and the text of the dialog
     *
     * @param evt - has the window event as a parameter for when the help dialog
     * activated
     */
    private void helpDialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_helpDialogWindowActivated
        helpLabel.setText("<html>+ Each category has buttons where you can <br>&nbsp view the translations<br> + You can test yourself in the test mode"
                + "<br>+ Your score will be saved after a test<br> + Use the home button to go back home <br> + Use the exit button to leave the game at any time </html>");
    }//GEN-LAST:event_helpDialogWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arm;
    private javax.swing.JButton armsButton;
    private javax.swing.JDialog armsDialog;
    private javax.swing.JPanel armsPanel;
    private javax.swing.JLabel back;
    private javax.swing.JButton backButton;
    private javax.swing.JDialog backDialog;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel boca;
    private javax.swing.JLabel bodypartTitle;
    private javax.swing.JPanel bodypartsPanel;
    private javax.swing.JLabel brazo;
    private javax.swing.JLabel cuello;
    private javax.swing.JLabel ear;
    private javax.swing.JButton earsButton;
    private javax.swing.JDialog earsDialog;
    private javax.swing.JPanel earsPanel;
    private javax.swing.JLabel espalda;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton eyeButton;
    private javax.swing.JLabel eyes;
    private javax.swing.JDialog eyesDialog;
    private javax.swing.JPanel eyesPanel;
    private javax.swing.JLabel feet;
    private javax.swing.JButton feetButton;
    private javax.swing.JDialog feetDialog;
    private javax.swing.JPanel feetPanel;
    private javax.swing.JLabel hand;
    private javax.swing.JButton handButton;
    private javax.swing.JDialog handsDialog;
    private javax.swing.JPanel handsPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JDialog helpDialog;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton legButton;
    private javax.swing.JLabel legs;
    private javax.swing.JDialog legsDialog;
    private javax.swing.JPanel legsPanel;
    private javax.swing.JLabel manos;
    private javax.swing.JLabel mouth;
    private javax.swing.JButton mouthButton;
    private javax.swing.JDialog mouthDialog;
    private javax.swing.JPanel mouthPanel;
    private javax.swing.JLabel nariz;
    private javax.swing.JLabel neck;
    private javax.swing.JButton neckButton;
    private javax.swing.JDialog neckDialog;
    private javax.swing.JPanel neckPanel;
    private javax.swing.JLabel nose;
    private javax.swing.JButton noseButton;
    private javax.swing.JDialog noseDialog;
    private javax.swing.JPanel nosePanel;
    private javax.swing.JLabel ojos;
    private javax.swing.JButton ok;
    private javax.swing.JButton okArms;
    private javax.swing.JButton okBack;
    private javax.swing.JButton okEars;
    private javax.swing.JButton okEyes;
    private javax.swing.JButton okFeet;
    private javax.swing.JButton okHands;
    private javax.swing.JButton okLegs;
    private javax.swing.JButton okMouth;
    private javax.swing.JButton okNeck;
    private javax.swing.JButton okNose;
    private javax.swing.JLabel orejas;
    private javax.swing.JLabel piernas;
    private javax.swing.JLabel pies;
    private javax.swing.JLabel rules;
    private javax.swing.JLabel skeleton;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables

    /**
     * this method sets the parameter database with the local variable database
     *
     * @param db - this takes in the spanish database variable
     */
    public void setDatabase(SpanishDB db) {
        this.db = db;
    }

    /**
     * this method returns the spanish database
     *
     * @return SpanishDB - this returns the database
     */
    public SpanishDB getDatabase() {
        return this.db;
    }

}
