package espanolapp;



/**
 * this class is the frame for when the color radio button is pressed in the
 * main frame, it stores the buttons and components of the frame
 *
 * @author Jazmin Vagha 16941106
 */
public class ColorButton extends javax.swing.JFrame {

    private SpanishDB db;

    /**
     * this method is the constructor for the class which calls the method to
     * initialize the components
     *
     * @param datab - an object of the main database, accesses the table in the
     * database
     */
    public ColorButton(SpanishDB datab) {
        initComponents();
        db = datab;
        colorPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redDialog = new javax.swing.JDialog();
        red = new javax.swing.JPanel();
        rojo = new javax.swing.JLabel();
        okRed = new javax.swing.JButton();
        orangeDialog = new javax.swing.JDialog();
        orange = new javax.swing.JPanel();
        okOrange = new javax.swing.JButton();
        naranja = new javax.swing.JLabel();
        yellowDialog = new javax.swing.JDialog();
        yellow = new javax.swing.JPanel();
        amarillo = new javax.swing.JLabel();
        okYellow = new javax.swing.JButton();
        greenDialog = new javax.swing.JDialog();
        green = new javax.swing.JPanel();
        verde = new javax.swing.JLabel();
        okGreen = new javax.swing.JButton();
        blueDialog = new javax.swing.JDialog();
        blue = new javax.swing.JPanel();
        azul = new javax.swing.JLabel();
        okBlue = new javax.swing.JButton();
        purpleDialog = new javax.swing.JDialog();
        purple = new javax.swing.JPanel();
        marado = new javax.swing.JLabel();
        okPurple = new javax.swing.JButton();
        pinkDialog = new javax.swing.JDialog();
        pink = new javax.swing.JPanel();
        rosado = new javax.swing.JLabel();
        okPink = new javax.swing.JButton();
        whiteDialog = new javax.swing.JDialog();
        white = new javax.swing.JPanel();
        blanco = new javax.swing.JLabel();
        okWhite = new javax.swing.JButton();
        greyDialog = new javax.swing.JDialog();
        grey = new javax.swing.JPanel();
        okGrey = new javax.swing.JButton();
        gris = new javax.swing.JLabel();
        brownDialog = new javax.swing.JDialog();
        brown = new javax.swing.JPanel();
        marron = new javax.swing.JLabel();
        okBrown = new javax.swing.JButton();
        blackDialog = new javax.swing.JDialog();
        black = new javax.swing.JPanel();
        negro = new javax.swing.JLabel();
        okBlack = new javax.swing.JButton();
        helpDialog = new javax.swing.JDialog();
        helpPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        helpTitle = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        colorPanel = new javax.swing.JPanel();
        redButton = new javax.swing.JButton();
        orangeButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        purpleButton = new javax.swing.JButton();
        pinkButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        greyButton = new javax.swing.JButton();
        brownButton = new javax.swing.JButton();
        blackButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        colorTitle = new javax.swing.JLabel();
        rules = new javax.swing.JLabel();
        test = new javax.swing.JButton();

        redDialog.setTitle("                                 RED");
        redDialog.setBackground(new java.awt.Color(255, 0, 0));
        redDialog.setFocusable(false);
        redDialog.setResizable(false);
        redDialog.setSize(new java.awt.Dimension(315, 218));
        redDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        red.setBackground(new java.awt.Color(255, 255, 255));
        red.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rojo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        rojo.setText("ROJO");
        red.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        okRed.setText("OK");
        okRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okRedActionPerformed(evt);
            }
        });
        red.add(okRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        redDialog.getContentPane().add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        orangeDialog.setTitle("                              ORANGE");
        orangeDialog.setResizable(false);
        orangeDialog.setSize(new java.awt.Dimension(315, 218));
        orangeDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orange.setBackground(new java.awt.Color(255, 255, 255));
        orange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okOrange.setText("OK");
        okOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okOrangeActionPerformed(evt);
            }
        });
        orange.add(okOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        naranja.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        naranja.setText("NARANJA");
        orange.add(naranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        orangeDialog.getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        yellowDialog.setTitle("                              YELLOW");
        yellowDialog.setResizable(false);
        yellowDialog.setSize(new java.awt.Dimension(315, 218));
        yellowDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yellow.setBackground(new java.awt.Color(255, 255, 255));
        yellow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amarillo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        amarillo.setText("AMARILLO");
        yellow.add(amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        okYellow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okYellow.setText("OK");
        okYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okYellowActionPerformed(evt);
            }
        });
        yellow.add(okYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        yellowDialog.getContentPane().add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        greenDialog.setTitle("                               GREEN");
        greenDialog.setResizable(false);
        greenDialog.setSize(new java.awt.Dimension(315, 218));
        greenDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        green.setBackground(new java.awt.Color(255, 255, 255));
        green.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verde.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        verde.setText("VERDE");
        green.add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        okGreen.setText("OK");
        okGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okGreenActionPerformed(evt);
            }
        });
        green.add(okGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        greenDialog.getContentPane().add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        blueDialog.setTitle("                                 BLUE");
        blueDialog.setResizable(false);
        blueDialog.setSize(new java.awt.Dimension(315, 218));
        blueDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blue.setBackground(new java.awt.Color(255, 255, 255));
        blue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        azul.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        azul.setText("AZUL");
        blue.add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        okBlue.setText("OK");
        okBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBlueActionPerformed(evt);
            }
        });
        blue.add(okBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        blueDialog.getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        purpleDialog.setTitle("                              PURPLE");
        purpleDialog.setResizable(false);
        purpleDialog.setSize(new java.awt.Dimension(315, 218));
        purpleDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purple.setBackground(new java.awt.Color(255, 255, 255));
        purple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marado.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        marado.setText("MARADO");
        purple.add(marado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        okPurple.setText("OK");
        okPurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPurpleActionPerformed(evt);
            }
        });
        purple.add(okPurple, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        purpleDialog.getContentPane().add(purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        pinkDialog.setTitle("                                PINK");
        pinkDialog.setResizable(false);
        pinkDialog.setSize(new java.awt.Dimension(315, 218));
        pinkDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pink.setBackground(new java.awt.Color(255, 255, 255));
        pink.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rosado.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        rosado.setText("ROSADO");
        pink.add(rosado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        okPink.setText("OK");
        okPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPinkActionPerformed(evt);
            }
        });
        pink.add(okPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        pinkDialog.getContentPane().add(pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        whiteDialog.setTitle("                    WHITE");
        whiteDialog.setSize(new java.awt.Dimension(315, 218));
        whiteDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        white.setBackground(new java.awt.Color(255, 255, 255));
        white.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blanco.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        blanco.setText("BLANCO");
        white.add(blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        okWhite.setText("OK");
        okWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okWhiteActionPerformed(evt);
            }
        });
        white.add(okWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        whiteDialog.getContentPane().add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 315, 218));

        greyDialog.setTitle("                                 GREY");
        greyDialog.setBackground(new java.awt.Color(255, 255, 255));
        greyDialog.setResizable(false);
        greyDialog.setSize(new java.awt.Dimension(315, 218));
        greyDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grey.setBackground(new java.awt.Color(255, 255, 255));
        grey.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okGrey.setText("OK");
        okGrey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okGreyActionPerformed(evt);
            }
        });
        grey.add(okGrey, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        gris.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        gris.setText("GRIS");
        gris.setToolTipText("");
        grey.add(gris, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        greyDialog.getContentPane().add(grey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        brownDialog.setTitle("                                BROWN");
        brownDialog.setBackground(new java.awt.Color(255, 255, 255));
        brownDialog.setResizable(false);
        brownDialog.setSize(new java.awt.Dimension(315, 218));
        brownDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brown.setBackground(new java.awt.Color(255, 255, 255));
        brown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marron.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        marron.setText("MARRON");
        brown.add(marron, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        okBrown.setText("OK");
        okBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBrownActionPerformed(evt);
            }
        });
        brown.add(okBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        brownDialog.getContentPane().add(brown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        blackDialog.setTitle("                                BLACK");
        blackDialog.setBackground(new java.awt.Color(255, 255, 255));
        blackDialog.setResizable(false);
        blackDialog.setSize(new java.awt.Dimension(315, 218));
        blackDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        black.setBackground(new java.awt.Color(255, 255, 255));
        black.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        negro.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        negro.setText("NEGRO");
        black.add(negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 186, 56));

        okBlack.setText("OK");
        okBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBlackActionPerformed(evt);
            }
        });
        black.add(okBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        blackDialog.getContentPane().add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        helpDialog.setTitle("                                                    HELP MENU");
        helpDialog.setBackground(new java.awt.Color(255, 255, 255));
        helpDialog.setFocusable(false);
        helpDialog.setResizable(false);
        helpDialog.setSize(new java.awt.Dimension(490, 310));
        helpDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                helpDialogWindowActivated(evt);
            }
        });
        helpDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpPanel.setBackground(new java.awt.Color(255, 196, 4));
        helpPanel.setFocusable(false);
        helpPanel.setPreferredSize(new java.awt.Dimension(490, 310));
        helpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        helpPanel.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 40));

        helpLabel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        helpLabel.setText("Use the home button to go back home");
        helpPanel.add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        helpTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        helpTitle.setText("HELP MENU");
        helpPanel.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        helpDialog.getContentPane().add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(656, 404));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 34));

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(0, 0, 222));
        helpButton.setText("HELP");
        helpButton.setBorder(null);
        helpButton.setBorderPainted(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 34));

        colorPanel.setBackground(new java.awt.Color(255, 196, 4));
        colorPanel.setPreferredSize(new java.awt.Dimension(656, 410));
        colorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redButton.setBackground(new java.awt.Color(255, 0, 0));
        redButton.setBorder(null);
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        colorPanel.add(redButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 50, 49));

        orangeButton.setBackground(java.awt.Color.orange);
        orangeButton.setBorder(null);
        orangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeButtonActionPerformed(evt);
            }
        });
        colorPanel.add(orangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 50, 49));

        yellowButton.setBackground(java.awt.Color.yellow);
        yellowButton.setBorder(null);
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        colorPanel.add(yellowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 50, 49));

        greenButton.setBackground(java.awt.Color.green);
        greenButton.setBorder(null);
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });
        colorPanel.add(greenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 50, 49));

        blueButton.setBackground(java.awt.Color.blue);
        blueButton.setBorder(null);
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });
        colorPanel.add(blueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, 49));

        purpleButton.setBackground(new java.awt.Color(172, 0, 255));
        purpleButton.setBorder(null);
        purpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleButtonActionPerformed(evt);
            }
        });
        colorPanel.add(purpleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 50, 49));

        pinkButton.setBackground(new java.awt.Color(255, 153, 204));
        pinkButton.setBorder(null);
        pinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkButtonActionPerformed(evt);
            }
        });
        colorPanel.add(pinkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 50, 49));

        whiteButton.setBackground(new java.awt.Color(255, 255, 255));
        whiteButton.setBorder(null);
        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });
        colorPanel.add(whiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 50, 49));

        greyButton.setBackground(new java.awt.Color(153, 153, 153));
        greyButton.setBorder(null);
        greyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greyButtonActionPerformed(evt);
            }
        });
        colorPanel.add(greyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 50, 49));

        brownButton.setBackground(new java.awt.Color(73, 0, 0));
        brownButton.setBorder(null);
        brownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownButtonActionPerformed(evt);
            }
        });
        colorPanel.add(brownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 49));

        blackButton.setBackground(new java.awt.Color(0, 0, 0));
        blackButton.setBorder(null);
        blackButton.setVerifyInputWhenFocusTarget(false);
        blackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackButtonActionPerformed(evt);
            }
        });
        colorPanel.add(blackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 50, 49));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(250, 0, 0));
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        colorPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 70, 34));

        colorTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        colorTitle.setText("COLORS");
        colorPanel.add(colorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 210, -1));

        rules.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        rules.setText("Press the colors to see their translations");
        colorPanel.add(rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 350, -1));

        test.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        test.setText("TAKE THE TEST");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        colorPanel.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        getContentPane().add(colorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * this method exits the program when the exit button is pressed
     *
     * @param evt - has the action event as a parameter for when the exit button
     * pressed
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    /**
     * this method takes you to the back to the start frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the home button
     * pressed
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new EspanolApp(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed
    /**
     * this method is the action for when the red button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the red button
     * pressed
     */
    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        redDialog.setVisible(true);
    }//GEN-LAST:event_redButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the red
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okRedActionPerformed
        redDialog.dispose();
    }//GEN-LAST:event_okRedActionPerformed
    /**
     * this method is the action for when the orange button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the orange
     * button pressed
     */
    private void orangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeButtonActionPerformed
        orangeDialog.setVisible(true);
    }//GEN-LAST:event_orangeButtonActionPerformed
    /**
     * this method is the action for when the yellow button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the yellow
     * button pressed
     */
    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        yellowDialog.setVisible(true);
    }//GEN-LAST:event_yellowButtonActionPerformed
    /**
     * this method is the action for when the green button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the green
     * button pressed
     */
    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        greenDialog.setVisible(true);
    }//GEN-LAST:event_greenButtonActionPerformed
    /**
     * this method is the action for when the blue button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the blue button
     * pressed
     */
    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        blueDialog.setVisible(true);
    }//GEN-LAST:event_blueButtonActionPerformed
    /**
     * this method is the action for when the purple button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the purple
     * button pressed
     */
    private void purpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleButtonActionPerformed
        purpleDialog.setVisible(true);
    }//GEN-LAST:event_purpleButtonActionPerformed
    /**
     * this method is the action for when the pink button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the pink button
     * pressed
     */
    private void pinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkButtonActionPerformed
        pinkDialog.setVisible(true);
    }//GEN-LAST:event_pinkButtonActionPerformed
    /**
     * this method is the action for when the white button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the white
     * button pressed
     */
    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteButtonActionPerformed
        whiteDialog.setVisible(true);
    }//GEN-LAST:event_whiteButtonActionPerformed
    /**
     * this method is the action for when the grey button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the grey button
     * pressed
     */
    private void greyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greyButtonActionPerformed
        greyDialog.setVisible(true);
    }//GEN-LAST:event_greyButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the orange
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okOrangeActionPerformed
        orangeDialog.dispose();
    }//GEN-LAST:event_okOrangeActionPerformed
    /**
     * this method is the actions that occur when the ok button in the yellow
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okYellowActionPerformed
        yellowDialog.dispose();
    }//GEN-LAST:event_okYellowActionPerformed
    /**
     * this method is the actions that occur when the ok button in the green
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okGreenActionPerformed
        greenDialog.dispose();
    }//GEN-LAST:event_okGreenActionPerformed
    /**
     * this method is the actions that occur when the ok button in the blue
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBlueActionPerformed
        blueDialog.dispose();
    }//GEN-LAST:event_okBlueActionPerformed
    /**
     * this method is the actions that occur when the ok button in the purple
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPurpleActionPerformed
        purpleDialog.dispose();
    }//GEN-LAST:event_okPurpleActionPerformed
    /**
     * this method is the actions that occur when the ok button in the pink
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPinkActionPerformed
        pinkDialog.dispose();
    }//GEN-LAST:event_okPinkActionPerformed
    /**
     * this method is the actions that occur when the ok button in the white
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okWhiteActionPerformed
        whiteDialog.dispose();
    }//GEN-LAST:event_okWhiteActionPerformed
    /**
     * this method is the actions that occur when the ok button in the grey
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okGreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okGreyActionPerformed
        greyDialog.dispose();
    }//GEN-LAST:event_okGreyActionPerformed
    /**
     * this method is the action for when the arms button is pressed, a black
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the black
     * button pressed
     */
    private void blackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackButtonActionPerformed
        blackDialog.setVisible(true);
    }//GEN-LAST:event_blackButtonActionPerformed
    /**
     * this method is the action for when the arms button is pressed, a brown
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the brown
     * button pressed
     */
    private void brownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownButtonActionPerformed
        brownDialog.setVisible(true);
    }//GEN-LAST:event_brownButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the brown
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBrownActionPerformed
        brownDialog.dispose();
    }//GEN-LAST:event_okBrownActionPerformed
    /**
     * this method is the actions that occur when the ok button in the black
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBlackActionPerformed
        blackDialog.dispose();
    }//GEN-LAST:event_okBlackActionPerformed
    /**
     * this method opens the test frame of the colors when the take the test
     * button is pressed on the color frame
     *
     * @param evt - has the action event as a parameter for when the take the
     * test button pressed
     */
    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        new ColorTest(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testActionPerformed
    /**
     * this method is the actions that occur when the help button is pressed, a
     * dialog pops up with general help on the program
     *
     * @param evt - has the action event as a parameter for when help button
     * pressed
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpDialog.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed
    /**
     * this method is the actions that occur when the ok button in the help
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        helpDialog.dispose();
    }//GEN-LAST:event_okActionPerformed
    /**
     * this method activates the help dialog when the program when the help
     * button is pressed and the text of the dialog
     *
     * @param evt - has the window event as a parameter for when the help dialog
     * activated
     */
    private void helpDialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_helpDialogWindowActivated
        helpLabel.setText("<html>+ Each category has buttons where you can <br>&nbsp view the translations<br> + You can test yourself in the test mode"
                + "<br>+ Your score will be saved after a test<br> + Use the home button to go back home <br> + Use the exit button to leave the game at any time </html>");
    }//GEN-LAST:event_helpDialogWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel azul;
    private javax.swing.JPanel black;
    private javax.swing.JButton blackButton;
    private javax.swing.JDialog blackDialog;
    private javax.swing.JLabel blanco;
    private javax.swing.JPanel blue;
    private javax.swing.JButton blueButton;
    private javax.swing.JDialog blueDialog;
    private javax.swing.JPanel brown;
    private javax.swing.JButton brownButton;
    private javax.swing.JDialog brownDialog;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JLabel colorTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel green;
    private javax.swing.JButton greenButton;
    private javax.swing.JDialog greenDialog;
    private javax.swing.JPanel grey;
    private javax.swing.JButton greyButton;
    private javax.swing.JDialog greyDialog;
    private javax.swing.JLabel gris;
    private javax.swing.JButton helpButton;
    private javax.swing.JDialog helpDialog;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel marado;
    private javax.swing.JLabel marron;
    private javax.swing.JLabel naranja;
    private javax.swing.JLabel negro;
    private javax.swing.JButton ok;
    private javax.swing.JButton okBlack;
    private javax.swing.JButton okBlue;
    private javax.swing.JButton okBrown;
    private javax.swing.JButton okGreen;
    private javax.swing.JButton okGrey;
    private javax.swing.JButton okOrange;
    private javax.swing.JButton okPink;
    private javax.swing.JButton okPurple;
    private javax.swing.JButton okRed;
    private javax.swing.JButton okWhite;
    private javax.swing.JButton okYellow;
    private javax.swing.JPanel orange;
    private javax.swing.JButton orangeButton;
    private javax.swing.JDialog orangeDialog;
    private javax.swing.JPanel pink;
    private javax.swing.JButton pinkButton;
    private javax.swing.JDialog pinkDialog;
    private javax.swing.JPanel purple;
    private javax.swing.JButton purpleButton;
    private javax.swing.JDialog purpleDialog;
    private javax.swing.JPanel red;
    private javax.swing.JButton redButton;
    private javax.swing.JDialog redDialog;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel rosado;
    private javax.swing.JLabel rules;
    private javax.swing.JButton test;
    private javax.swing.JLabel verde;
    private javax.swing.JPanel white;
    private javax.swing.JButton whiteButton;
    private javax.swing.JDialog whiteDialog;
    private javax.swing.JPanel yellow;
    private javax.swing.JButton yellowButton;
    private javax.swing.JDialog yellowDialog;
    // End of variables declaration//GEN-END:variables

    /**
     * this method sets the parameter database with the local variable database
     *
     * @param db - this takes in the spanish database variable
     */
    public void setDatabase(SpanishDB db) {
        this.db = db;
    }

    /**
     * this method returns the spanish database
     *
     * @return SpanishDB - this returns the database
     */
    public SpanishDB getDatabase() {
        return this.db;
    }

}
