package espanolapp;



/**
 *
 * @author Jazmin Vagha 16941106 This class is the main class that starts the
 * program and initializes the frame, it stores the buttons and components of
 * the frame
 *
 */
public class EspanolApp extends javax.swing.JFrame {

    private static SpanishDB db;

    /**
     * this method is the constructor for the class which calls the method to
     * initialize the components
     *
     * @param datab - an object of the main database, accesses the table in the
     * database
     */
    public EspanolApp(SpanishDB datab) {
        initComponents();
        db = datab;
        database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpDialog = new javax.swing.JDialog();
        helpPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        helpTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        basicSpanish = new javax.swing.JLabel();
        rules = new javax.swing.JLabel();
        choose = new javax.swing.JPanel();
        numberButton = new javax.swing.JRadioButton();
        colorButton = new javax.swing.JRadioButton();
        bodypartButton = new javax.swing.JRadioButton();
        spainBg = new javax.swing.JLabel();

        helpDialog.setTitle("                                                    HELP MENU");
        helpDialog.setBackground(new java.awt.Color(255, 255, 255));
        helpDialog.setFocusable(false);
        helpDialog.setResizable(false);
        helpDialog.setSize(new java.awt.Dimension(490, 310));
        helpDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                helpDialogWindowActivated(evt);
            }
        });
        helpDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpPanel.setBackground(new java.awt.Color(255, 196, 4));
        helpPanel.setFocusable(false);
        helpPanel.setPreferredSize(new java.awt.Dimension(490, 310));
        helpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        helpPanel.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 40));

        helpLabel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        helpLabel.setText("Use the home button to go back home");
        helpPanel.add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        helpTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        helpTitle.setText("HELP MENU");
        helpPanel.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        helpDialog.getContentPane().add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(656, 404));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 70, 34));

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(255, 0, 0));
        helpButton.setText("HELP");
        helpButton.setBorder(null);
        helpButton.setBorderPainted(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 34));

        bg.setBackground(new java.awt.Color(255, 196, 4));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basicSpanish.setBackground(new java.awt.Color(0, 0, 0));
        basicSpanish.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        basicSpanish.setText("LEARN BASIC SPANISH");
        bg.add(basicSpanish, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 480, 50));

        rules.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        rules.setText("Choose one of the following to learn:");
        bg.add(rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        choose.setBackground(new java.awt.Color(255, 196, 4));
        choose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberButton.setBackground(new java.awt.Color(255, 196, 4));
        numberButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        numberButton.setText("Numbers");
        numberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButtonActionPerformed(evt);
            }
        });
        choose.add(numberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 159, 34));

        colorButton.setBackground(new java.awt.Color(255, 196, 4));
        colorButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        colorButton.setText("Colors");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });
        choose.add(colorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 112, 36));

        bodypartButton.setBackground(new java.awt.Color(255, 196, 4));
        bodypartButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 19)); // NOI18N
        bodypartButton.setText("Body Parts");
        bodypartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodypartButtonActionPerformed(evt);
            }
        });
        choose.add(bodypartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, -1, -1));

        bg.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, 170));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 404));
        bg.getAccessibleContext().setAccessibleDescription("");

        spainBg.setText("                     LEARN BASIC SPANISH");
        getContentPane().add(spainBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this method exits the program when the exit button is pressed
     *
     * @param evt - has the action event as a parameter for when the exit button
     * pressed
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    /**
     * this method takes you to the body part frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the body part
     * button pressed
     */
    private void bodypartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodypartButtonActionPerformed
        new BodypartsButton(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bodypartButtonActionPerformed

    /**
     * this method takes you to the color frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the color
     * button pressed
     */
    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        new ColorButton(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_colorButtonActionPerformed

    /**
     * this method takes you to the number frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the number
     * button pressed
     */
    private void numberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButtonActionPerformed
        new NumberButton(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_numberButtonActionPerformed

    /**
     * this method is the actions that occur when the ok button in the help
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        helpDialog.dispose();
    }//GEN-LAST:event_okActionPerformed
    /**
     * this method activates the help dialog when the program when the help
     * button is pressed and the text of the dialog
     *
     * @param evt - has the window event as a parameter for when the help dialog
     * activated
     */
    private void helpDialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_helpDialogWindowActivated
        helpLabel.setText("<html>+ Each category has buttons where you can <br>&nbsp view the translations<br> + You can test yourself in the test mode"
                + "<br>+ Your score will be saved after a test<br> + Use the home button to go back home <br> + Use the exit button to leave the game at any time </html>");
    }//GEN-LAST:event_helpDialogWindowActivated
    /**
     * this method is the actions that occur when the help button is pressed, a
     * dialog pops up with general help on the program
     *
     * @param evt - has the action event as a parameter for when help button
     * pressed
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpDialog.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * this method is the main that runs the program
     *
     * @param arg
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspanolApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspanolApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspanolApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspanolApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspanolApp(db).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicSpanish;
    private javax.swing.JPanel bg;
    private javax.swing.JRadioButton bodypartButton;
    private javax.swing.JPanel choose;
    private javax.swing.JRadioButton colorButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JDialog helpDialog;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JRadioButton numberButton;
    private javax.swing.JButton ok;
    private javax.swing.JLabel rules;
    private javax.swing.JLabel spainBg;
    // End of variables declaration//GEN-END:variables

    /**
     * this method initializes the database and creates the connection
     */
    private void database() {
        db = new SpanishDB();
        db.createConnection();
    }

    /**
     * this method sets the parameter database with the local variable database
     *
     * @param db - this takes in the spanish database variable
     */
    public void setDatabase(SpanishDB db) {
        this.db = db;
    }

    /**
     * this method returns the spanish database
     *
     * @return SpanishDB - this returns the database
     */
    public SpanishDB getDatabase() {
        return this.db;
    }
}
