package espanolapp;



/**
 * this class is the frame for when the number radio button is pressed in the
 * main frame, it stores the buttons and components of the frame
 *
 * @author Jazmin Vagha 16941106
 */
public class NumberButton extends javax.swing.JFrame {

    SpanishDB db;

    /**
     * this method is the constructor for the class which calls the method to
     * initialize the components
     *
     * @param datab - an object of the main database, accesses the table in the
     * database
     */
    public NumberButton(SpanishDB datab) {
        db = datab;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogOne = new javax.swing.JDialog();
        one = new javax.swing.JPanel();
        UNO = new javax.swing.JLabel();
        okOne = new javax.swing.JButton();
        dialogTwo = new javax.swing.JDialog();
        two = new javax.swing.JPanel();
        dos = new javax.swing.JLabel();
        okTwo = new javax.swing.JButton();
        dialogThree = new javax.swing.JDialog();
        three = new javax.swing.JPanel();
        tres = new javax.swing.JLabel();
        okThree = new javax.swing.JButton();
        dialogFour = new javax.swing.JDialog();
        four = new javax.swing.JPanel();
        cuatro = new javax.swing.JLabel();
        okFour = new javax.swing.JButton();
        dialogFive = new javax.swing.JDialog();
        five = new javax.swing.JPanel();
        cinco = new javax.swing.JLabel();
        okFive = new javax.swing.JButton();
        dialogSix = new javax.swing.JDialog();
        six = new javax.swing.JPanel();
        seis = new javax.swing.JLabel();
        okSix = new javax.swing.JButton();
        dialogSeven = new javax.swing.JDialog();
        seven = new javax.swing.JPanel();
        seite = new javax.swing.JLabel();
        okSeven = new javax.swing.JButton();
        dialogEight = new javax.swing.JDialog();
        eight = new javax.swing.JPanel();
        ocho = new javax.swing.JLabel();
        okEight = new javax.swing.JButton();
        dialogNine = new javax.swing.JDialog();
        nine = new javax.swing.JPanel();
        nueve = new javax.swing.JLabel();
        okNine = new javax.swing.JButton();
        dialogTen = new javax.swing.JDialog();
        ten = new javax.swing.JPanel();
        diez = new javax.swing.JLabel();
        okTen = new javax.swing.JButton();
        helpDialog = new javax.swing.JDialog();
        helpPanel = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        helpTitle = new javax.swing.JLabel();
        numberTitle = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        numberPanel = new javax.swing.JPanel();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        rules = new javax.swing.JLabel();
        buttonTen = new javax.swing.JButton();
        test = new javax.swing.JButton();

        dialogOne.setTitle("                                 ONE");
        dialogOne.setAlwaysOnTop(true);
        dialogOne.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogOne.setResizable(false);
        dialogOne.setSize(new java.awt.Dimension(315, 218));
        dialogOne.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setPreferredSize(new java.awt.Dimension(315, 218));
        one.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNO.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        UNO.setText("UNO");
        one.add(UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        okOne.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okOne.setText("OK");
        okOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okOneActionPerformed(evt);
            }
        });
        one.add(okOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogOne.getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogTwo.setTitle("                                 TWO");
        dialogTwo.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogTwo.setResizable(false);
        dialogTwo.setSize(new java.awt.Dimension(315, 218));
        dialogTwo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setPreferredSize(new java.awt.Dimension(315, 218));
        two.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        dos.setText("dos");
        two.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        okTwo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okTwo.setText("OK");
        okTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okTwoActionPerformed(evt);
            }
        });
        two.add(okTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogTwo.getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogThree.setTitle("                                 THREE");
        dialogThree.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogThree.setResizable(false);
        dialogThree.setSize(new java.awt.Dimension(315, 218));
        dialogThree.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setPreferredSize(new java.awt.Dimension(315, 218));
        three.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tres.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        tres.setText("TRES");
        three.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        okThree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okThree.setText("OK");
        okThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okThreeActionPerformed(evt);
            }
        });
        three.add(okThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogThree.getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogFour.setTitle("                                 FOUR");
        dialogFour.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogFour.setResizable(false);
        dialogFour.setSize(new java.awt.Dimension(315, 218));
        dialogFour.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setPreferredSize(new java.awt.Dimension(315, 218));
        four.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuatro.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        cuatro.setText("CUATRO");
        four.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        okFour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okFour.setText("OK");
        okFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okFourActionPerformed(evt);
            }
        });
        four.add(okFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogFour.getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogFive.setTitle("                                 FIVE");
        dialogFive.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogFive.setResizable(false);
        dialogFive.setSize(new java.awt.Dimension(315, 218));
        dialogFive.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        five.setBackground(new java.awt.Color(255, 255, 255));
        five.setPreferredSize(new java.awt.Dimension(315, 218));
        five.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cinco.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        cinco.setText("CINCO");
        five.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        okFive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okFive.setText("OK");
        okFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okFiveActionPerformed(evt);
            }
        });
        five.add(okFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogFive.getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogSix.setTitle("                          SIX");
        dialogSix.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogSix.setSize(new java.awt.Dimension(315, 218));
        dialogSix.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        six.setBackground(new java.awt.Color(255, 255, 255));
        six.setPreferredSize(new java.awt.Dimension(315, 218));
        six.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seis.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        seis.setText("SEIS");
        six.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        okSix.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okSix.setText("OK");
        okSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSixActionPerformed(evt);
            }
        });
        six.add(okSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogSix.getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogSeven.setTitle("                                 SEVEN");
        dialogSeven.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogSeven.setResizable(false);
        dialogSeven.setSize(new java.awt.Dimension(315, 218));
        dialogSeven.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seven.setBackground(new java.awt.Color(255, 255, 255));
        seven.setPreferredSize(new java.awt.Dimension(315, 218));
        seven.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seite.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        seite.setText("SEITE");
        seven.add(seite, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        okSeven.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okSeven.setText("OK");
        okSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSevenActionPerformed(evt);
            }
        });
        seven.add(okSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogSeven.getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogEight.setTitle("                                 EIGHT");
        dialogEight.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogEight.setResizable(false);
        dialogEight.setSize(new java.awt.Dimension(315, 218));
        dialogEight.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eight.setBackground(new java.awt.Color(255, 255, 255));
        eight.setPreferredSize(new java.awt.Dimension(315, 218));
        eight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ocho.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        ocho.setText("OCHO");
        eight.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        okEight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okEight.setText("OK");
        okEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEightActionPerformed(evt);
            }
        });
        eight.add(okEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogEight.getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogNine.setTitle("                                 NINE");
        dialogNine.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogNine.setResizable(false);
        dialogNine.setSize(new java.awt.Dimension(315, 218));
        dialogNine.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nine.setBackground(new java.awt.Color(255, 255, 255));
        nine.setPreferredSize(new java.awt.Dimension(315, 218));
        nine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nueve.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        nueve.setText("NUEVE");
        nine.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        okNine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okNine.setText("OK");
        okNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNineActionPerformed(evt);
            }
        });
        nine.add(okNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogNine.getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        dialogTen.setTitle("                                 TEN");
        dialogTen.setMinimumSize(new java.awt.Dimension(315, 218));
        dialogTen.setResizable(false);
        dialogTen.setSize(new java.awt.Dimension(315, 218));
        dialogTen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ten.setBackground(new java.awt.Color(255, 255, 255));
        ten.setPreferredSize(new java.awt.Dimension(315, 218));
        ten.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diez.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        diez.setText("DIEZ");
        ten.add(diez, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        okTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okTen.setText("OK");
        okTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okTenActionPerformed(evt);
            }
        });
        ten.add(okTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 40));

        dialogTen.getContentPane().add(ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        helpDialog.setTitle("                                                    HELP MENU");
        helpDialog.setBackground(new java.awt.Color(255, 255, 255));
        helpDialog.setFocusable(false);
        helpDialog.setResizable(false);
        helpDialog.setSize(new java.awt.Dimension(490, 310));
        helpDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                helpDialogWindowActivated(evt);
            }
        });
        helpDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpPanel.setBackground(new java.awt.Color(255, 196, 4));
        helpPanel.setFocusable(false);
        helpPanel.setPreferredSize(new java.awt.Dimension(490, 310));
        helpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        helpPanel.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 40));

        helpLabel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        helpLabel.setText("Use the home button to go back home");
        helpPanel.add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        helpTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        helpTitle.setText("HELP MENU");
        helpPanel.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        helpDialog.getContentPane().add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(656, 404));
        setResizable(false);
        setSize(new java.awt.Dimension(656, 404));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberTitle.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 32)); // NOI18N
        numberTitle.setText("NUMBERS");
        getContentPane().add(numberTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 221, -1));

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(0, 0, 222));
        helpButton.setText("HELP");
        helpButton.setBorder(null);
        helpButton.setBorderPainted(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 34));

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 222));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 34));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(250, 0, 0));
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.setFocusable(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 70, 34));

        numberPanel.setBackground(new java.awt.Color(255, 196, 4));
        numberPanel.setName(""); // NOI18N
        numberPanel.setPreferredSize(new java.awt.Dimension(656, 380));
        numberPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonOne.setBackground(java.awt.Color.white);
        buttonOne.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonOne.setText("1");
        buttonOne.setToolTipText("");
        buttonOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });
        numberPanel.add(buttonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 60));

        buttonTwo.setBackground(java.awt.Color.white);
        buttonTwo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonTwo.setText("2");
        buttonTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });
        numberPanel.add(buttonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, 59));

        buttonThree.setBackground(java.awt.Color.white);
        buttonThree.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonThree.setText("3");
        buttonThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });
        numberPanel.add(buttonThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 60, 59));

        buttonFive.setBackground(java.awt.Color.white);
        buttonFive.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonFive.setText("5");
        buttonFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });
        numberPanel.add(buttonFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 59));

        buttonSix.setBackground(java.awt.Color.white);
        buttonSix.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonSix.setText("6");
        buttonSix.setToolTipText("");
        buttonSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });
        numberPanel.add(buttonSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 60, 59));

        buttonSeven.setBackground(java.awt.Color.white);
        buttonSeven.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonSeven.setText("7");
        buttonSeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });
        numberPanel.add(buttonSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 60, 59));

        buttonEight.setBackground(java.awt.Color.white);
        buttonEight.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonEight.setText("8");
        buttonEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });
        numberPanel.add(buttonEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 60, 59));

        buttonNine.setBackground(java.awt.Color.white);
        buttonNine.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonNine.setText("9");
        buttonNine.setToolTipText("");
        buttonNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });
        numberPanel.add(buttonNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 60, 59));

        buttonFour.setBackground(java.awt.Color.white);
        buttonFour.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonFour.setText("4");
        buttonFour.setToolTipText("");
        buttonFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });
        numberPanel.add(buttonFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 60, 59));

        rules.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        rules.setText("Press the numbers to see their translations");
        numberPanel.add(rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        buttonTen.setBackground(java.awt.Color.white);
        buttonTen.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        buttonTen.setText("10");
        buttonTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTenActionPerformed(evt);
            }
        });
        numberPanel.add(buttonTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 59));

        test.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        test.setText("TAKE THE TEST");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        numberPanel.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        getContentPane().add(numberPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * this method exits the program when the exit button is pressed
     *
     * @param evt - has the action event as a parameter for when the exit button
     * pressed
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    /**
     * this method takes you to the back to the start frame when it is pressed
     *
     * @param evt - has the action event as a parameter for when the home button
     * pressed
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new EspanolApp(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed
    /**
     * this method is the action for when the one button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the one button
     * pressed
     */
    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        dialogOne.setVisible(true);
    }//GEN-LAST:event_buttonOneActionPerformed
    /**
     * this method is the action for when the ten button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the ten button
     * pressed
     */
    private void buttonTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTenActionPerformed
        dialogTen.setVisible(true);
    }//GEN-LAST:event_buttonTenActionPerformed
    /**
     * this method is the action for when the six button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the six button
     * pressed
     */
    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        dialogSix.setVisible(true);
    }//GEN-LAST:event_buttonSixActionPerformed
    /**
     * this method is the actions that occur when the ok button in the one
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okOneActionPerformed
        dialogOne.dispose();
    }//GEN-LAST:event_okOneActionPerformed
    /**
     * this method is the actions that occur when the ok button in the two
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okTwoActionPerformed
        dialogTwo.dispose();
    }//GEN-LAST:event_okTwoActionPerformed
    /**
     * this method is the actions that occur when the ok button in the three
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okThreeActionPerformed
        dialogThree.dispose();
    }//GEN-LAST:event_okThreeActionPerformed
    /**
     * this method is the actions that occur when the ok button in the four
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okFourActionPerformed
        dialogFour.dispose();
    }//GEN-LAST:event_okFourActionPerformed
    /**
     * this method is the actions that occur when the ok button in the five
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okFiveActionPerformed
        dialogFive.dispose();
    }//GEN-LAST:event_okFiveActionPerformed
    /**
     * this method is the actions that occur when the ok button in the six
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSixActionPerformed
        dialogSix.dispose();
    }//GEN-LAST:event_okSixActionPerformed
    /**
     * this method is the actions that occur when the ok button in the seven
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSevenActionPerformed
        dialogSeven.dispose();
    }//GEN-LAST:event_okSevenActionPerformed
    /**
     * this method is the actions that occur when the ok button in the eight
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEightActionPerformed
        dialogEight.dispose();
    }//GEN-LAST:event_okEightActionPerformed
    /**
     * this method is the actions that occur when the ok button in the nine
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNineActionPerformed
        dialogNine.dispose();
    }//GEN-LAST:event_okNineActionPerformed
    /**
     * this method is the actions that occur when the ok button in the ten
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okTenActionPerformed
        dialogTen.dispose();
    }//GEN-LAST:event_okTenActionPerformed
    /**
     * this method is the action for when the two button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the two button
     * pressed
     */
    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        dialogTwo.setVisible(true);
    }//GEN-LAST:event_buttonTwoActionPerformed
    /**
     * this method is the action for when the three button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the three
     * button pressed
     */
    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        dialogThree.setVisible(true);
    }//GEN-LAST:event_buttonThreeActionPerformed
    /**
     * this method is the action for when the five button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the five button
     * pressed
     */
    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        dialogFive.setVisible(true);
    }//GEN-LAST:event_buttonFiveActionPerformed
    /**
     * this method is the action for when the seven button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the seven
     * button pressed
     */
    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        dialogSeven.setVisible(true);
    }//GEN-LAST:event_buttonSevenActionPerformed
    /**
     * this method is the action for when the eight button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the eight
     * button pressed
     */
    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        dialogEight.setVisible(true);
    }//GEN-LAST:event_buttonEightActionPerformed
    /**
     * this method is the action for when the nine button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the nine button
     * pressed
     */
    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        dialogNine.setVisible(true);
    }//GEN-LAST:event_buttonNineActionPerformed
    /**
     * this method is the action for when the four button is pressed, a dialog
     * will come up with the spanish translation of the word
     *
     * @param evt - has the action event as a parameter for when the four button
     * pressed
     */
    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        dialogFour.setVisible(true);
    }//GEN-LAST:event_buttonFourActionPerformed
    /**
     * this method opens the test frame of the numbers when the take the test
     * button is pressed on the number frame
     *
     * @param evt - has the action event as a parameter for when the take the
     * test button pressed
     */
    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        new NumberTest(db).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testActionPerformed
    /**
     * this method is the actions that occur when the ok button in the help
     * dialog is pressed and the dialog disappears
     *
     * @param evt - has the action event as a parameter for when ok button
     * pressed
     */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        helpDialog.dispose();
    }//GEN-LAST:event_okActionPerformed
    /**
     * this method activates the help dialog when the program when the help
     * button is pressed and the text of the dialog
     *
     * @param evt - has the window event as a parameter for when the help dialog
     * activated
     */
    private void helpDialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_helpDialogWindowActivated
        helpLabel.setText("<html>+ Each category has buttons where you can <br>&nbsp view the translations<br> + You can test yourself in the test mode"
                + "<br>+ Your score will be saved after a test<br> + Use the home button to go back home <br> + Use the exit button to leave the game at any time </html>");
    }//GEN-LAST:event_helpDialogWindowActivated
    /**
     * this method is the actions that occur when the help button is pressed, a
     * dialog pops up with general help on the program
     *
     * @param evt - has the action event as a parameter for when help button
     * pressed
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpDialog.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UNO;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonTen;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cuatro;
    private javax.swing.JDialog dialogEight;
    private javax.swing.JDialog dialogFive;
    private javax.swing.JDialog dialogFour;
    private javax.swing.JDialog dialogNine;
    private javax.swing.JDialog dialogOne;
    private javax.swing.JDialog dialogSeven;
    private javax.swing.JDialog dialogSix;
    private javax.swing.JDialog dialogTen;
    private javax.swing.JDialog dialogThree;
    private javax.swing.JDialog dialogTwo;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel dos;
    private javax.swing.JPanel eight;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel five;
    private javax.swing.JPanel four;
    private javax.swing.JButton helpButton;
    private javax.swing.JDialog helpDialog;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel nine;
    private javax.swing.JLabel nueve;
    private javax.swing.JPanel numberPanel;
    private javax.swing.JLabel numberTitle;
    private javax.swing.JLabel ocho;
    private javax.swing.JButton ok;
    private javax.swing.JButton okEight;
    private javax.swing.JButton okFive;
    private javax.swing.JButton okFour;
    private javax.swing.JButton okNine;
    private javax.swing.JButton okOne;
    private javax.swing.JButton okSeven;
    private javax.swing.JButton okSix;
    private javax.swing.JButton okTen;
    private javax.swing.JButton okThree;
    private javax.swing.JButton okTwo;
    private javax.swing.JPanel one;
    private javax.swing.JLabel rules;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel seite;
    private javax.swing.JPanel seven;
    private javax.swing.JPanel six;
    private javax.swing.JPanel ten;
    private javax.swing.JButton test;
    private javax.swing.JPanel three;
    private javax.swing.JLabel tres;
    private javax.swing.JPanel two;
    // End of variables declaration//GEN-END:variables

    /**
     * this method sets the parameter database with the local variable database
     *
     * @param db - this takes in the spanish database variable
     */
    public void setDatabase(SpanishDB db) {
        this.db = db;
    }

    /**
     * this method returns the spanish database
     *
     * @return SpanishDB - this returns the database
     */
    public SpanishDB getDatabase() {
        return this.db;
    }
}
